[package]
name = "once-hir"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "High-level Intermediate Representation for the Once language"

[dependencies]
once-parse = { path = "../once-parse" }
once-lex = { path = "../once-lex" }
thiserror = { workspace = true }
serde = { workspace = true }
indexmap = "2.0"
